name: Spell Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run cSpell
        uses: streetsidesoftware/cspell-action@dcd03dc3e8a59ec2e360d0c62db517baa0b4bb6d # v7.2.0
        with:
          files: |
            **/*.{md,yaml,yml}
          config: '.github/workflows/utils/cspell.json'
          check_dot_files: true
