name: Hash OBS Automation App PEM

on:
  workflow_dispatch:
  push:
  pull_request_target:

jobs:
  hash-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print SHA-256 hash of OBS_AUTOMATION_APP_PEM
        shell: bash
        env:
          OBS_AUTOMATION_APP_PEM: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
        run: |
          printf "%s" "$OBS_AUTOMATION_APP_PEM" | sha256sum
